OGGDIR=/media/b1/oggs

cp $OGGDIR/acdc/back_in_black.m3u ./acdc/back_in_black.m3u
cp $OGGDIR/antal_dorati_london_symphony_orchestra/enesco__liszt_roumanian__hungarian_rhapsodies/enesco__liszt_roumanian__hungarian_rhapsodies.m3u ./antal_dorati_london_symphony_orchestra/enesco__liszt_roumanian__hungarian_rhapsodies/enesco__liszt_roumanian__hungarian_rhapsodies.m3u
cp $OGGDIR/antibalas/Antibalas-Antibalas/Antibalas-Antibalas.ogg.m3u ./antibalas/Antibalas-Antibalas/Antibalas-Antibalas.ogg.m3u
cp $OGGDIR/antibalas/Antibalas-Antibalas/antibalas.m3u ./antibalas/Antibalas-Antibalas/antibalas.m3u
cp $OGGDIR/antibalas/who_is_this_america/who_is_this_america.m3u ./antibalas/who_is_this_america/who_is_this_america.m3u
cp $OGGDIR/art_blakey_and_the_jazz_messen/a_night_in_tunisia/a_night_in_tunisia.m3u ./art_blakey_and_the_jazz_messen/a_night_in_tunisia/a_night_in_tunisia.m3u
cp $OGGDIR/astrud_gilberto/verve_jazz_masters_9.m3u ./astrud_gilberto/verve_jazz_masters_9.m3u
cp $OGGDIR/bach_johann_sebastian/goldberg_variations__vinikour_disc_1/goldberg_variations__vinikour_disc_1.m3u ./bach_johann_sebastian/goldberg_variations__vinikour_disc_1/goldberg_variations__vinikour_disc_1.m3u
cp $OGGDIR/bach_johann_sebastian/goldberg_variations__vinikour_disc_2/goldberg_variations__vinikour_disc_2.m3u ./bach_johann_sebastian/goldberg_variations__vinikour_disc_2/goldberg_variations__vinikour_disc_2.m3u
cp $OGGDIR/beastie-boys_-_check-your-head/check_your_head.m3u ./beastie-boys_-_check-your-head/check_your_head.m3u
cp $OGGDIR/beastie_boys/licensed_to_ill_1986/licensed_to_ill_1986.m3u ./beastie_boys/licensed_to_ill_1986/licensed_to_ill_1986.m3u
cp $OGGDIR/beatles/magical_mystery_tour.m3u ./beatles/magical_mystery_tour.m3u
cp $OGGDIR/beatles/revolver.m3u ./beatles/revolver.m3u
cp $OGGDIR/beck/mutations.m3u ./beck/mutations.m3u
cp $OGGDIR/beethoven_ludwig_van/symphonies_3_eroica_and_4/symphony_no_3_eroica_and_symphony_no_4.m3u ./beethoven_ludwig_van/symphonies_3_eroica_and_4/symphony_no_3_eroica_and_symphony_no_4.m3u
cp $OGGDIR/beethoven_ludwig_van/symphonies_no7_in_a_major_op_92__no8_in_f_major_op_93/symphonies_no7_in_a_major_op_92__no8_in_f_major_op_93.m3u ./beethoven_ludwig_van/symphonies_no7_in_a_major_op_92__no8_in_f_major_op_93/symphonies_no7_in_a_major_op_92__no8_in_f_major_op_93.m3u
cp $OGGDIR/beethoven_ludwig_van/symphonies_nos_1_2/symphonies_nos1__2.m3u ./beethoven_ludwig_van/symphonies_nos_1_2/symphonies_nos1__2.m3u
cp $OGGDIR/beethoven_ludwig_van/symphonies_nos_5_and_6/symphonies_5_and_6.m3u ./beethoven_ludwig_van/symphonies_nos_5_and_6/symphonies_5_and_6.m3u
cp $OGGDIR/beethoven_ludwig_van/symphony_no_9_in_d_minor_op_125/symphony_no_9_in_d_minor_op_125.m3u ./beethoven_ludwig_van/symphony_no_9_in_d_minor_op_125/symphony_no_9_in_d_minor_op_125.m3u
cp $OGGDIR/beethoven/the_five_piano_concertos__rudolf_serkin_seiji_ozawa_boston_symphony_orch_cd1.m3u ./beethoven/the_five_piano_concertos__rudolf_serkin_seiji_ozawa_boston_symphony_orch_cd1.m3u
cp $OGGDIR/beethoven/the_five_piano_concertos__rudolf_serkin_seiji_ozawa_boston_symphony_orch_cd2.m3u ./beethoven/the_five_piano_concertos__rudolf_serkin_seiji_ozawa_boston_symphony_orch_cd2.m3u
cp $OGGDIR/beethoven/the_five_piano_concertos__rudolf_serkin_seiji_ozawa_boston_symphony_orch_cd3.m3u ./beethoven/the_five_piano_concertos__rudolf_serkin_seiji_ozawa_boston_symphony_orch_cd3.m3u
cp $OGGDIR/benjamin_britten/young_persons_guide_to_the_orchestra_etc/benjamin_britten-young_persons_guide_to_the_orchestra_etc.m3u ./benjamin_britten/young_persons_guide_to_the_orchestra_etc/benjamin_britten-young_persons_guide_to_the_orchestra_etc.m3u
cp $OGGDIR/benny_goodman/best_of_big_bands.m3u ./benny_goodman/best_of_big_bands.m3u
cp $OGGDIR/bernstein_nypo/tchaikovsky_4_etc/tchaikovsky_4_etc.m3u ./bernstein_nypo/tchaikovsky_4_etc/tchaikovsky_4_etc.m3u
cp $OGGDIR/bernstein_nypo/tchaikovsky_symphony_no_5__marche_slave__1812_overture/tchaikovsky_symphony_no_5__marche_slave__1812_overture.m3u ./bernstein_nypo/tchaikovsky_symphony_no_5__marche_slave__1812_overture/tchaikovsky_symphony_no_5__marche_slave__1812_overture.m3u
cp $OGGDIR/bill_frisell/before_we_were_born.m3u ./bill_frisell/before_we_were_born.m3u
cp $OGGDIR/bill_frisell/with_dave_holland_and_elvin_jones/with_dave_holland_and_elvin_jones.m3u ./bill_frisell/with_dave_holland_and_elvin_jones/with_dave_holland_and_elvin_jones.m3u
cp $OGGDIR/binary_system/from_the_epicenter.m3u ./binary_system/from_the_epicenter.m3u
cp $OGGDIR/black_sabbath/reunion__1.m3u ./black_sabbath/reunion__1.m3u
cp $OGGDIR/black_sabbath/reunion_2.m3u ./black_sabbath/reunion_2.m3u
cp $OGGDIR/bobby_previte/the_23_constellations_of_joan_mir/the_23_constellations_of_joan_mir.m3u ./bobby_previte/the_23_constellations_of_joan_mir/the_23_constellations_of_joan_mir.m3u
cp $OGGDIR/bobby_previte/the_coalition_of_the_willing/the_coalition_of_the_willing.m3u ./bobby_previte/the_coalition_of_the_willing/the_coalition_of_the_willing.m3u
cp $OGGDIR/bobby_previte/weather_clear__track_fast/weather_clear__track_fast.m3u ./bobby_previte/weather_clear__track_fast/weather_clear__track_fast.m3u
cp $OGGDIR/bob_log_iii/log_bomb.m3u ./bob_log_iii/log_bomb.m3u
cp $OGGDIR/britten_slatkin_purcell/young_persons_guide_to_the_orchestra/young_persons_guide_to_the_orchestra.m3u ./britten_slatkin_purcell/young_persons_guide_to_the_orchestra/young_persons_guide_to_the_orchestra.m3u
cp $OGGDIR/buddy_rich/jazz_masters.m3u ./buddy_rich/jazz_masters.m3u
cp $OGGDIR/bud_powell/time_waits_the_amazing_bud_pow/time_waits.m3u ./bud_powell/time_waits_the_amazing_bud_pow/time_waits.m3u
cp $OGGDIR/built_to_spill/ancient_melodies_of_the_future.m3u ./built_to_spill/ancient_melodies_of_the_future.m3u
cp $OGGDIR/built_to_spill/caustic_resin.m3u ./built_to_spill/caustic_resin.m3u
cp $OGGDIR/built_to_spill/keep_it_like_a_secret.m3u ./built_to_spill/keep_it_like_a_secret.m3u
cp $OGGDIR/built_to_spill/perfect_from_now_on/perfect_from_now_on.m3u ./built_to_spill/perfect_from_now_on/perfect_from_now_on.m3u
cp $OGGDIR/Built_To_Spill_-_Ultimate_Alternative_Wavers/uaw.m3u ./Built_To_Spill_-_Ultimate_Alternative_Wavers/uaw.m3u
cp $OGGDIR/butthole_surfers/electriclarryland.m3u ./butthole_surfers/electriclarryland.m3u
cp $OGGDIR/carla_kihlstedt/2_foot_yard/2_foot_yard.m3u ./carla_kihlstedt/2_foot_yard/2_foot_yard.m3u
cp $OGGDIR/cash_johnny/disc_1.m3u ./cash_johnny/disc_1.m3u
cp $OGGDIR/cash_johnny/disc_2.m3u ./cash_johnny/disc_2.m3u
cp $OGGDIR/chadwick.m3u ./chadwick.m3u
cp $OGGDIR/chadwick_ref.m3u ./chadwick_ref.m3u
cp $OGGDIR/Charles_Mingus_-_Mingus_Ah_Um/mingus_ah-um.m3u ./Charles_Mingus_-_Mingus_Ah_Um/mingus_ah-um.m3u
cp $OGGDIR/Charles_Mingus_-_Mingus_Ah_Um/mingus_ah_um.m3u ./Charles_Mingus_-_Mingus_Ah_Um/mingus_ah_um.m3u
cp $OGGDIR/charles_mingus/mingus_at_carnegie_hall.m3u ./charles_mingus/mingus_at_carnegie_hall.m3u
cp $OGGDIR/charlie_parker/the_best_of_the_bird/thebestofthebird.m3u ./charlie_parker/the_best_of_the_bird/thebestofthebird.m3u
cp $OGGDIR/claude_debussy/essential_debussy_CD1.m3u ./claude_debussy/essential_debussy_CD1.m3u
cp $OGGDIR/claude_debussy/essential_debussy_CD2.m3u ./claude_debussy/essential_debussy_CD2.m3u
cp $OGGDIR/copper/traveling/traveling.m3u ./copper/traveling/traveling.m3u
cp $OGGDIR/count_basie__joe_williams/breakfast_dance_and_barbecue/breakfast_dance_and_barbec.m3u ./count_basie__joe_williams/breakfast_dance_and_barbecue/breakfast_dance_and_barbec.m3u
cp $OGGDIR/david_garibaldi/future_sounds/future_sounds.m3u ./david_garibaldi/future_sounds/future_sounds.m3u
cp $OGGDIR/dean_martin/greatest_hits.m3u ./dean_martin/greatest_hits.m3u
cp $OGGDIR/duke_ellington/duke_ellingtons_greatest_h.m3u ./duke_ellington/duke_ellingtons_greatest_h.m3u
cp $OGGDIR/emil_bovbjerg_septet/the_color_7/the_color_7.m3u ./emil_bovbjerg_septet/the_color_7/the_color_7.m3u
cp $OGGDIR/erik_satie/piano_works.m3u ./erik_satie/piano_works.m3u
cp $OGGDIR/esquivel/music_from_a_sparkling_pla.m3u ./esquivel/music_from_a_sparkling_pla.m3u
cp $OGGDIR/ethan_snyder_and_friends/chadwicks_mp471_stereo_remix/chadwicks_mp471_stereo_remix.m3u ./ethan_snyder_and_friends/chadwicks_mp471_stereo_remix/chadwicks_mp471_stereo_remix.m3u
cp $OGGDIR/eyvind_kang/the_story_of_iceland/the_story_of_iceland.m3u ./eyvind_kang/the_story_of_iceland/the_story_of_iceland.m3u
cp $OGGDIR/faith_no_more/king_for_a_day_fool_for_a_lifetime/king_for_a_day_fool_for_a_lifetime.m3u ./faith_no_more/king_for_a_day_fool_for_a_lifetime/king_for_a_day_fool_for_a_lifetime.m3u
cp $OGGDIR/Faith_No_More_-_Who_Cares_A_LotCD1/who_cares_a_lot_disc_one.m3u ./Faith_No_More_-_Who_Cares_A_LotCD1/who_cares_a_lot_disc_one.m3u
cp $OGGDIR/Faith_No_More_-_Who_Cares_A_LotCD2/who_cares_a_lot_disc_two.m3u ./Faith_No_More_-_Who_Cares_A_LotCD2/who_cares_a_lot_disc_two.m3u
cp $OGGDIR/fantmas/fantmas.m3u ./fantmas/fantmas.m3u
cp $OGGDIR/fantomas/the_directors_cut/fantomas-the_directors_cut.m3u ./fantomas/the_directors_cut/fantomas-the_directors_cut.m3u
cp $OGGDIR/fire_of_space/handbasket/handbasket.m3u ./fire_of_space/handbasket/handbasket.m3u
cp $OGGDIR/frank_black/teenager_of_the_year/teenager_of_the_year.m3u ./frank_black/teenager_of_the_year/teenager_of_the_year.m3u
cp $OGGDIR/frank_sinatra/sinatra_reprise__the_very_good_years.m3u ./frank_sinatra/sinatra_reprise__the_very_good_years.m3u
cp $OGGDIR/fred_hersch__bill_frisell/songs_we_know/songs_we_know.m3u ./fred_hersch__bill_frisell/songs_we_know/songs_we_know.m3u
cp $OGGDIR/geddy_lee/my_favorite_headache.m3u ./geddy_lee/my_favorite_headache.m3u
cp $OGGDIR/george_winston/plains/plains.m3u ./george_winston/plains/plains.m3u
cp $OGGDIR/hal_willner/weird_nightmare_meditation.m3u ./hal_willner/weird_nightmare_meditation.m3u
cp $OGGDIR/hank_williams/the_best_of_hank_williams_the_millenium_collection.m3u ./hank_williams/the_best_of_hank_williams_the_millenium_collection.m3u
cp $OGGDIR/ja_granelly_and_mr_lucky/el_oh_el_ay/el_oh_el_ay.m3u ./ja_granelly_and_mr_lucky/el_oh_el_ay/el_oh_el_ay.m3u
cp $OGGDIR/jah_wobble_and_bill_laswell/radioaxiom__a_dub_transmission/radioaxiom__a_dub_transmission.m3u ./jah_wobble_and_bill_laswell/radioaxiom__a_dub_transmission/radioaxiom__a_dub_transmission.m3u
cp $OGGDIR/jamie_saft/sovlanut.m3u ./jamie_saft/sovlanut.m3u
cp $OGGDIR/jamie_saft/sovlanut/sovlanut2.m3u ./jamie_saft/sovlanut/sovlanut2.m3u
cp $OGGDIR/jamie_saft/sovlanut/sovlanut.m3u ./jamie_saft/sovlanut/sovlanut.m3u
cp $OGGDIR/jascha_heifetz_violin/beethovenbrahms_violin_concertos.m3u ./jascha_heifetz_violin/beethovenbrahms_violin_concertos.m3u
cp $OGGDIR/jeff_alex_mike/chadwicks_berklee_analog_project/chadwicks_berklee_analog_project.m3u ./jeff_alex_mike/chadwicks_berklee_analog_project/chadwicks_berklee_analog_project.m3u
cp $OGGDIR/jeff_alex_mike/chadwicks_berklee_sessions/chadwicks_berklee_sessions.m3u ./jeff_alex_mike/chadwicks_berklee_sessions/chadwicks_berklee_sessions.m3u
cp $OGGDIR/jerseyband/christmasband/christmasband.m3u ./jerseyband/christmasband/christmasband.m3u
cp $OGGDIR/jerseyband/little_bag_of_feet_for_shoes/little_bag_of_feet_for_shoes.m3u ./jerseyband/little_bag_of_feet_for_shoes/little_bag_of_feet_for_shoes.m3u
cp $OGGDIR/jim_black/splay/splay.m3u ./jim_black/splay/splay.m3u
cp $OGGDIR/jim_hall/dialogues.m3u ./jim_hall/dialogues.m3u
cp $OGGDIR/joe_lovano/joe_lovano_quartet_live_at.m3u ./joe_lovano/joe_lovano_quartet_live_at.m3u
cp $OGGDIR/Joey_Baron_-_Killer_Joey/killer_joey.m3u ./Joey_Baron_-_Killer_Joey/killer_joey.m3u
cp $OGGDIR/joey_baron_-_tongue_in_groove/tongue_in_groove.m3u ./joey_baron_-_tongue_in_groove/tongue_in_groove.m3u
cp $OGGDIR/john_coltrane/interstellar_space/interstellar_space.m3u ./john_coltrane/interstellar_space/interstellar_space.m3u
cp $OGGDIR/john_coltrane/live_at_the_village_vanguard_a/live_at_the_village_vangua.m3u ./john_coltrane/live_at_the_village_vanguard_a/live_at_the_village_vangua.m3u
cp $OGGDIR/john_lennon/the_collection.m3u ./john_lennon/the_collection.m3u
cp $OGGDIR/johnny_cash/american_recordings/american_recordings.m3u ./johnny_cash/american_recordings/american_recordings.m3u
cp $OGGDIR/john_zorn/elegy.m3u ./john_zorn/elegy.m3u
cp $OGGDIR/john_zorn/music_romance_ii_taboo_and_exile.m3u ./john_zorn/music_romance_ii_taboo_and_exile.m3u
cp $OGGDIR/john_zorn/naked_city.m3u ./john_zorn/naked_city.m3u
cp $OGGDIR/john_zorn__naked_city/torture_garden.m3u ./john_zorn__naked_city/torture_garden.m3u
cp $OGGDIR/john_zorn/the_gift.m3u ./john_zorn/the_gift.m3u
cp $OGGDIR/jo_jones/the_everest_years/the_everest_years.m3u ./jo_jones/the_everest_years/the_everest_years.m3u
cp $OGGDIR/Keith_Jarret-Gary_Peacock-Jack_DeJohnette_Always_Let_Me_Go/always_let_me_go2.m3u ./Keith_Jarret-Gary_Peacock-Jack_DeJohnette_Always_Let_Me_Go/always_let_me_go2.m3u
cp $OGGDIR/Keith_Jarrett-Gary_Peacock-Jack_Dejonette_Always_Let_Me_Go/always_let_me_go1.m3u ./Keith_Jarrett-Gary_Peacock-Jack_Dejonette_Always_Let_Me_Go/always_let_me_go1.m3u
cp $OGGDIR/larry_coryell/lady_coryell/lady_coryell.m3u ./larry_coryell/lady_coryell/lady_coryell.m3u
cp $OGGDIR/leonard_bernstein/the_final_concert/the_final_concert.m3u ./leonard_bernstein/the_final_concert/the_final_concert.m3u
cp $OGGDIR/living_language/inflight_dutch/inflight_dutch.m3u ./living_language/inflight_dutch/inflight_dutch.m3u
cp $OGGDIR/luke_gibleon/bright_morning_star/bright_morning_star.m3u ./luke_gibleon/bright_morning_star/bright_morning_star.m3u
cp $OGGDIR/lynn_harrell/j_s_bach_cello_suites_disk_1/j_s_bach_cello_suites_disk_1.m3u ./lynn_harrell/j_s_bach_cello_suites_disk_1/j_s_bach_cello_suites_disk_1.m3u
cp $OGGDIR/lynn_harrell/j_s_bach_cello_suites_disk_2_of_2/j_s_bach_cello_suites_disk_2_of_2.m3u ./lynn_harrell/j_s_bach_cello_suites_disk_2_of_2/j_s_bach_cello_suites_disk_2_of_2.m3u
cp $OGGDIR/lynss/traje__dragon_bait__drudge/traje__dragon_bait__drudge.m3u ./lynss/traje__dragon_bait__drudge/traje__dragon_bait__drudge.m3u
cp $OGGDIR/Maggid-Maggid/Maggid-Maggid.m3u ./Maggid-Maggid/Maggid-Maggid.m3u
cp $OGGDIR/Maggid-Maggid/Maggid-Maggid.ogg.m3u ./Maggid-Maggid/Maggid-Maggid.ogg.m3u
cp $OGGDIR/marc_ribot/shoe_string_symphonettes/shoe_string_symphonettes.m3u ./marc_ribot/shoe_string_symphonettes/shoe_string_symphonettes.m3u
cp $OGGDIR/Matt-Darriau-et-al_-_Ballin--the-Jack/ballin_the_jack.m3u ./Matt-Darriau-et-al_-_Ballin--the-Jack/ballin_the_jack.m3u
cp $OGGDIR/max_roach/featuring_the_legendary_hasaan_drums_unlimited/featuring_the_legendary_hasaan_drums_unlimited.m3u ./max_roach/featuring_the_legendary_hasaan_drums_unlimited/featuring_the_legendary_hasaan_drums_unlimited.m3u
cp $OGGDIR/melvins/houdini.m3u ./melvins/houdini.m3u
cp $OGGDIR/mike_watt/contemplating_the_engine_room/contemplating_the_engine_room.m3u ./mike_watt/contemplating_the_engine_room/contemplating_the_engine_room.m3u
cp $OGGDIR/miles_davis/best_of_miles_davis_quintet_19/best_of_miles_davis_quinte.m3u ./miles_davis/best_of_miles_davis_quintet_19/best_of_miles_davis_quinte.m3u
cp $OGGDIR/miles_davis/complete_in_a_silent_way_sessions/complete_in_a_silent_way_sessions.m3u ./miles_davis/complete_in_a_silent_way_sessions/complete_in_a_silent_way_sessions.m3u
cp $OGGDIR/miles_davis/kind_of_blue/kind_of_blue.m3u ./miles_davis/kind_of_blue/kind_of_blue.m3u
cp $OGGDIR/miles_davis/the_complete_bitches_brew_sessions_august_1969february_1970_disc_3/the_complete_bitches_brew_sessions_august_1969february_1970_disc_3.m3u ./miles_davis/the_complete_bitches_brew_sessions_august_1969february_1970_disc_3/the_complete_bitches_brew_sessions_august_1969february_1970_disc_3.m3u
cp $OGGDIR/miles_davis/the_complete_bitches_brew_sessions_disc_1/the_complete_bitches_brew_sessions_disc_1.m3u ./miles_davis/the_complete_bitches_brew_sessions_disc_1/the_complete_bitches_brew_sessions_disc_1.m3u
cp $OGGDIR/miles_davis/the_complete_bitches_brew_sessions_disc_2/the_complete_bitches_brew_sessions_disc_2.m3u ./miles_davis/the_complete_bitches_brew_sessions_disc_2/the_complete_bitches_brew_sessions_disc_2.m3u
cp $OGGDIR/miles_davis/the_complete_bitches_brew_sessions_disc_4/the_complete_bitches_brew_sessions_disc_4.m3u ./miles_davis/the_complete_bitches_brew_sessions_disc_4/the_complete_bitches_brew_sessions_disc_4.m3u
cp $OGGDIR/miles_davis/the_complete_in_a_silent_way_sessions__disc_1/the_complete_in_a_silent_way_sessions__disc_1.m3u ./miles_davis/the_complete_in_a_silent_way_sessions__disc_1/the_complete_in_a_silent_way_sessions__disc_1.m3u
cp $OGGDIR/miles_davis/the_complete_in_a_silent_way_sessions__disc_2/the_complete_in_a_silent_way_sessions__disc_2.m3u ./miles_davis/the_complete_in_a_silent_way_sessions__disc_2/the_complete_in_a_silent_way_sessions__disc_2.m3u
cp $OGGDIR/milhous/milhous/milhous.m3u ./milhous/milhous/milhous.m3u
cp $OGGDIR/minutemen/postmersh_vol_2/postmersh_vol_2.m3u ./minutemen/postmersh_vol_2/postmersh_vol_2.m3u
cp $OGGDIR/mother_vibration/mother_vibration.m3u ./mother_vibration/mother_vibration.m3u
cp $OGGDIR/Mr--Bungle_-_California/california.m3u ./Mr--Bungle_-_California/california.m3u
cp $OGGDIR/Mr--Bungle_-_Disco-Volante/disco_volante.m3u ./Mr--Bungle_-_Disco-Volante/disco_volante.m3u
cp $OGGDIR/Mr--Bungle_-_Mr--Bungle/mr_bungle.m3u ./Mr--Bungle_-_Mr--Bungle/mr_bungle.m3u
cp $OGGDIR/naked_city/black_box__leng_tche__disc.m3u ./naked_city/black_box__leng_tche__disc.m3u
cp $OGGDIR/ned_rothenberg/powerlines.m3u ./ned_rothenberg/powerlines.m3u
cp $OGGDIR/nels_cline_and_gregg_bendian/interstellar_space_revisted_the_music_of_john_coltrane/interstellar_space_revisted_the_music_of_john_coltrane.m3u ./nels_cline_and_gregg_bendian/interstellar_space_revisted_the_music_of_john_coltrane/interstellar_space_revisted_the_music_of_john_coltrane.m3u
cp $OGGDIR/nirvana/incesticide/incesticide.m3u ./nirvana/incesticide/incesticide.m3u
cp $OGGDIR/nirvana/in_utero/in_utero.m3u ./nirvana/in_utero/in_utero.m3u
cp $OGGDIR/noartist/unknown_disc/unknown_disc.m3u ./noartist/unknown_disc/unknown_disc.m3u
cp $OGGDIR/nori_kikuta/chadwicks_mp318_livetotwo/chadwicks_mp318_livetotwo.m3u ./nori_kikuta/chadwicks_mp318_livetotwo/chadwicks_mp318_livetotwo.m3u
cp $OGGDIR/n_rimskykorsakov/scheherazade__op_35_concertgebouw_orchestra/scheherazade__op_35_concertgebouw_orchestra.m3u ./n_rimskykorsakov/scheherazade__op_35_concertgebouw_orchestra/scheherazade__op_35_concertgebouw_orchestra.m3u
cp $OGGDIR/pat_metheny/bright_size_life.m3u ./pat_metheny/bright_size_life.m3u
cp $OGGDIR/pat_metheny/trio9900.m3u ./pat_metheny/trio9900.m3u
cp $OGGDIR/patsy_cline/12__greatest__hits.m3u ./patsy_cline/12__greatest__hits.m3u
cp $OGGDIR/peter_ilyich_tchaikovsky/symphonies_no_1_winter_dreams__no_2_little_russian/symphonies_no_1_winter_dreams__no_2_little_russian.m3u ./peter_ilyich_tchaikovsky/symphonies_no_1_winter_dreams__no_2_little_russian/symphonies_no_1_winter_dreams__no_2_little_russian.m3u
cp $OGGDIR/peter_ilyich_tchaikovsky/symphony_no_3_polish__romeo__juliet/symphony_no_3_polish__romeo__juliet.m3u ./peter_ilyich_tchaikovsky/symphony_no_3_polish__romeo__juliet/symphony_no_3_polish__romeo__juliet.m3u
cp $OGGDIR/pimsler/german_i__disc_4/german_i__disc_4.m3u ./pimsler/german_i__disc_4/german_i__disc_4.m3u
cp $OGGDIR/pimsleur/german1/german1.m3u ./pimsleur/german1/german1.m3u
cp $OGGDIR/pimsleur/german__disc_1/german__disc_1.m3u ./pimsleur/german__disc_1/german__disc_1.m3u
cp $OGGDIR/pimsleur_spanish/complete_course__user_manual/complete_course__user_manual.m3u ./pimsleur_spanish/complete_course__user_manual/complete_course__user_manual.m3u
cp $OGGDIR/pink_floyd/the_final_cut.m3u ./pink_floyd/the_final_cut.m3u
cp $OGGDIR/pixies/surfer_rosa__come_on_pilgrim.m3u ./pixies/surfer_rosa__come_on_pilgrim.m3u
cp $OGGDIR/playlists/coltrane_all.m3u ./playlists/coltrane_all.m3u
cp $OGGDIR/playlists/miles_58.m3u ./playlists/miles_58.m3u
cp $OGGDIR/praxis/1984.m3u ./praxis/1984.m3u
cp $OGGDIR/praxis/transmutation_mutatis_mutandis.m3u ./praxis/transmutation_mutatis_mutandis.m3u
cp $OGGDIR/primus/pork_soda/pork_soda.m3u ./primus/pork_soda/pork_soda.m3u
cp $OGGDIR/primus/salingtheseasofcheese/sailingtheseasofcheese.m3u ./primus/salingtheseasofcheese/sailingtheseasofcheese.m3u
cp $OGGDIR/primus/tales_from_the_punchbowl.m3u ./primus/tales_from_the_punchbowl.m3u
cp $OGGDIR/public_enemy/fear_of_a_black_planet/fear_of_a_black_planet.m3u ./public_enemy/fear_of_a_black_planet/fear_of_a_black_planet.m3u
cp $OGGDIR/public_enemy/yo_bum_rush_the_show/yo_bum_rush_the_show.m3u ./public_enemy/yo_bum_rush_the_show/yo_bum_rush_the_show.m3u
cp $OGGDIR/quincy_jones__sammy_nestico_or/basie__beyond.m3u ./quincy_jones__sammy_nestico_or/basie__beyond.m3u
cp $OGGDIR/radiohead/the_bends.m3u ./radiohead/the_bends.m3u
cp $OGGDIR/rather_r_dashing/best_of_rather_r_dashing/best_of_rather_r_dashing.m3u ./rather_r_dashing/best_of_rather_r_dashing/best_of_rather_r_dashing.m3u
cp $OGGDIR/rather_r_dashing/chadwicks_mp461_final_submission/chadwicks_mp461_final_submission.m3u ./rather_r_dashing/chadwicks_mp461_final_submission/chadwicks_mp461_final_submission.m3u
cp $OGGDIR/rather_r_dashing/chadwicks_mp461_project_overdubs/chadwicks_mp461_project_overdubs.m3u ./rather_r_dashing/chadwicks_mp461_project_overdubs/chadwicks_mp461_project_overdubs.m3u
cp $OGGDIR/robert_stillman/horses.m3u ./robert_stillman/horses.m3u
cp $OGGDIR/rodan/rusty.m3u ./rodan/rusty.m3u
cp $OGGDIR/Root-AgreeToDisagree/Root-AgreeToDisagree.ogg.m3u ./Root-AgreeToDisagree/Root-AgreeToDisagree.ogg.m3u
cp $OGGDIR/rush/retrospective_i.m3u ./rush/retrospective_i.m3u
cp $OGGDIR/secret_chiefs_3/book_m/book_m.m3u ./secret_chiefs_3/book_m/book_m.m3u
cp $OGGDIR/secret_chiefs_3/book_of_horizons/book_of_horizons.m3u ./secret_chiefs_3/book_of_horizons/book_of_horizons.m3u
cp $OGGDIR/secret_chiefs_3/eyes_of_flesh_eyes_of_flame/eyes_of_flesh_eyes_of_flame.m3u ./secret_chiefs_3/eyes_of_flesh_eyes_of_flame/eyes_of_flesh_eyes_of_flame.m3u
cp $OGGDIR/sephardic_tinge/morenica/morenica.m3u ./sephardic_tinge/morenica/morenica.m3u
cp $OGGDIR/sephardic_tinge/our_beautiful_garden_is_open/our_beautiful_garden_is_open.m3u ./sephardic_tinge/our_beautiful_garden_is_open/our_beautiful_garden_is_open.m3u
cp $OGGDIR/shelly_burgon__trevor_dunn/baltimore/baltimore.m3u ./shelly_burgon__trevor_dunn/baltimore/baltimore.m3u
cp $OGGDIR/sibelius_jean/the_symphonies__lorin_maazel_wiener_philharmoniker/the_symphonies__lorin_maazel_wiener_philharmoniker.m3u ./sibelius_jean/the_symphonies__lorin_maazel_wiener_philharmoniker/the_symphonies__lorin_maazel_wiener_philharmoniker.m3u
cp $OGGDIR/slint/tweez/tweez.m3u ./slint/tweez/tweez.m3u
cp $OGGDIR/slow_poke/slow_poke.m3u ./slow_poke/slow_poke.m3u
cp $OGGDIR/sonic_youth/sonic_youth/the_burning_spear.m3u ./sonic_youth/sonic_youth/the_burning_spear.m3u
cp $OGGDIR/sonic_youth/the_eternal/the_eternal.m3u ./sonic_youth/the_eternal/the_eternal.m3u
cp $OGGDIR/spiderland/spiderland.m3u ./spiderland/spiderland.m3u
cp $OGGDIR/squirrel_bait/squirrel_bait.m3u ./squirrel_bait/squirrel_bait.m3u
cp $OGGDIR/steelydanwalterbeckerdonaldfag/adecadeofsteelydanmcad1155.m3u ./steelydanwalterbeckerdonaldfag/adecadeofsteelydanmcad1155.m3u
cp $OGGDIR/stuntman/stuntman/stuntman.m3u ./stuntman/stuntman/stuntman.m3u
cp $OGGDIR/susie_ibarra/flower_after_flower.m3u ./susie_ibarra/flower_after_flower.m3u
cp $OGGDIR/susie_ibarra/folkloriko.m3u ./susie_ibarra/folkloriko.m3u
cp $OGGDIR/Susie-Ibarra_-_Songbird-Suite/songbird_suite.m3u ./Susie-Ibarra_-_Songbird-Suite/songbird_suite.m3u
cp $OGGDIR/talking_heads/speaking_in_tongues.m3u ./talking_heads/speaking_in_tongues.m3u
cp $OGGDIR/tchaikovsky_piotr_ilich/symphony_no_6_op_74__hamlet_op_67/symphony_no_6_op_74__hamlet_op_67.m3u ./tchaikovsky_piotr_ilich/symphony_no_6_op_74__hamlet_op_67/symphony_no_6_op_74__hamlet_op_67.m3u
cp $OGGDIR/the_beatles_one_greatest_hits/one.m3u ./the_beatles_one_greatest_hits/one.m3u
cp $OGGDIR/the_doobie_brothers/best_of_the_doobie_brother.m3u ./the_doobie_brothers/best_of_the_doobie_brother.m3u
cp $OGGDIR/The-For-Carnation_-_Marshmallows/marshmallows.m3u ./The-For-Carnation_-_Marshmallows/marshmallows.m3u
cp $OGGDIR/the_for_carnation/the_for_carnation/the_for_carnation.m3u ./the_for_carnation/the_for_carnation/the_for_carnation.m3u
cp $OGGDIR/the_halo_benders/god_dont_make_no_junk.m3u ./the_halo_benders/god_dont_make_no_junk.m3u
cp $OGGDIR/the_klezmatics_with_chava_alberstein/the_well/the_well.m3u ./the_klezmatics_with_chava_alberstein/the_well/the_well.m3u
cp $OGGDIR/thelonious_monk_genius_of_mode/geniusofmodernmusic.m3u ./thelonious_monk_genius_of_mode/geniusofmodernmusic.m3u
cp $OGGDIR/thelonious_monk_with_john_colt/thelonious_monk_with_john_colt/thelonious_monk_with_john_.m3u ./thelonious_monk_with_john_colt/thelonious_monk_with_john_colt/thelonious_monk_with_john_.m3u
cp $OGGDIR/the_minutemen/double_nickels_on_the_dime/double_nickels_on_the_dime.m3u ./the_minutemen/double_nickels_on_the_dime/double_nickels_on_the_dime.m3u
cp $OGGDIR/the_need/the_need_is_dead.m3u ./the_need/the_need_is_dead.m3u
cp $OGGDIR/tommy_flanagan_trio/overseas/overseas.m3u ./tommy_flanagan_trio/overseas/overseas.m3u
cp $OGGDIR/tomwaits/swordfishtrombones/swordfishtrombones.m3u ./tomwaits/swordfishtrombones/swordfishtrombones.m3u
cp $OGGDIR/treepeople/actual_reenactment/actual_reenactment.m3u ./treepeople/actual_reenactment/actual_reenactment.m3u
cp $OGGDIR/treepeople/actual_reenactment.m3u ./treepeople/actual_reenactment.m3u
cp $OGGDIR/treepeople/guilt_regret_and_embarrassment/guilt_regret_and_embarrassment.m3u ./treepeople/guilt_regret_and_embarrassment/guilt_regret_and_embarrassment.m3u
cp $OGGDIR/treepeople/guilt_regret_and_embarrassment.m3u ./treepeople/guilt_regret_and_embarrassment.m3u
cp $OGGDIR/treepeople/just_kidding/just_kidding.m3u ./treepeople/just_kidding/just_kidding.m3u
cp $OGGDIR/Treepeople_-_Something-Vicious-For-Tomorrow-Time-Whore/something_vicious.m3u ./Treepeople_-_Something-Vicious-For-Tomorrow-Time-Whore/something_vicious.m3u
cp $OGGDIR/trevor_dunns_trio_convulsant/trevor_dunns_trioconvulsant-sister_phantom_owl_fish.m3u ./trevor_dunns_trio_convulsant/trevor_dunns_trioconvulsant-sister_phantom_owl_fish.m3u
cp $OGGDIR/u_s_maple/long_hair_in_three_stages.m3u ./u_s_maple/long_hair_in_three_stages.m3u
cp $OGGDIR/van_morrison/moondance.m3u ./van_morrison/moondance.m3u
cp $OGGDIR/vernon_reid_elliot_sharp_david_torn/guitar_oblique.m3u ./vernon_reid_elliot_sharp_david_torn/guitar_oblique.m3u
cp $OGGDIR/wayne_horvitz_and_zony_mash/brand_spankin_new.m3u ./wayne_horvitz_and_zony_mash/brand_spankin_new.m3u
cp $OGGDIR/wayne_horvitz/the_president__miracle_mile.m3u ./wayne_horvitz/the_president__miracle_mile.m3u
cp $OGGDIR/wayne_horvitz/this_new_generation.m3u ./wayne_horvitz/this_new_generation.m3u
cp $OGGDIR/ween/godweensatan_25th_anniversary_edition/godweensatan_25th_anniversary_edition.m3u ./ween/godweensatan_25th_anniversary_edition/godweensatan_25th_anniversary_edition.m3u
cp $OGGDIR/Ween_-_Quebec/quebec.m3u ./Ween_-_Quebec/quebec.m3u
cp $OGGDIR/ween/the_mollusk/the_mollusk.m3u ./ween/the_mollusk/the_mollusk.m3u
cp $OGGDIR/ween/the_pod/the_pod.m3u ./ween/the_pod/the_pod.m3u
cp $OGGDIR/william_hooker_quartet/lifeline/lifeline.m3u ./william_hooker_quartet/lifeline/lifeline.m3u
cp $OGGDIR/william_hooker/shamballa/shamballa.m3u ./william_hooker/shamballa/shamballa.m3u
cp $OGGDIR/willie_nelson_and_ray_price/run_that_by_me_one_more_time/run_that_by_me_one_more_time.m3u ./willie_nelson_and_ray_price/run_that_by_me_one_more_time/run_that_by_me_one_more_time.m3u
cp $OGGDIR/wolpe/chadwicks_soundalike/chadwicks_soundalike.m3u ./wolpe/chadwicks_soundalike/chadwicks_soundalike.m3u
cp $OGGDIR/z_rock_hawaii/z_rock_hawaii/z_rock_hawaii.m3u ./z_rock_hawaii/z_rock_hawaii/z_rock_hawaii.m3u
